server:
  port: 8087
spring:
  application:
    name: micservice-getway
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8100/eureka/, http://admin:admin@127.0.0.1:9100/eureka/
    register-with-eureka: true
    fetch-registry: true
zuul:
  routes:
    micservice-order:
    micservice-item:
