server:
  port: 8080
#  port: 8079
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/te?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: micservice-item
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8100/eureka/
    register-with-eureka: true
    fetch-registry: true
management:
  health:
    db:
      enabled: true
    mail:
      enabled: true
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
mybatis:
  type-aliases-package: cn.micservice.item.pojo